volumes:
  data:
  data_test:
  export:
networks:
  idm_network:

services:
  postgres_db:
    image: docker.io/postgres:17-alpine
    container_name: postgres-server
    hostname: postgres-db
    ports:
      - 127.0.0.1:5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=idm
    volumes:
      - data:/var/lib/postgresql/data
      - export:/export
    networks:
      idm_network:
  test_postgres_db:
    image: docker.io/postgres:17-alpine
    container_name: test_postgres-server
    hostname: test_postgres-db
    ports:
      - 127.0.0.1:5434:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_idm
    volumes:
      - data_test:/var/lib/postgresql/data
      - export:/export
    networks:
      idm_network:

