version: "3"

volumes:
  data:
  export:
networks:
  idm_network:

services:
  postgres_db:
    image: docker.io/postgres:17-alpine
    container_name: postgres-server
    hostname: postgres-db
    ports:
      - 127.0.0.1:5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
    volumes:
      - data:/var/lib/postgresql/data
      - export:/export
    networks:
      idm_network:

